/// Flutter icons InterstellarIcons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  InterstellarIcons
///      fonts:
///       - asset: fonts/InterstellarIcons.ttf
///
///
///
import 'package:flutter/widgets.dart';

class InterstellarIcons {
  InterstellarIcons._();

  static const _kFontFam = 'InterstellarIcons';
  static const String? _kFontPkg = null;

  static const IconData profile =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData alarm =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eventTicket =
      IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData movieReel =
      IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}

class SvgAssets {
  static final SvgData starFireImage = SvgData('assets/images/star_fire.svg');
  static final SvgData playIcon = SvgData('assets/icons/play.svg');
  static final SvgData responseArrow =
      SvgData('assets/icons/respond_arrow.svg');
}

class SvgData {
  final String data;

  SvgData(this.data);
}

class PngAssets {
  static const appBarProfileIcon = 'assets/app_bar_profile_icon.png';
}
