name: interstellar_labs
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"
dependencies:
  cupertino_icons: ^1.0.2
  device_preview: ^1.0.0
  dio: ^4.0.4
  extended_image: ^6.0.1
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.2+1
  flutter_screenutil: ^5.3.1
  flutter_spinkit: ^5.1.0
  flutter_svg: ^1.0.3
  hive: ^2.0.5
  lazy_load_indexed_stack: ^0.1.3
  logger: ^1.1.0
  path_provider: ^2.0.9
  shimmer: ^2.0.0
  stacked: ^2.2.8
  stacked_services: ^0.8.17

dev_dependencies:
  build_runner: ^2.1.7
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.2
  stacked_generator: ^0.5.7
flutter:
  uses-material-design: true
  assets:
  - assets/
  - assets/images/
  - assets/icons/
  - assets/fonts/
  fonts:
    # - family: Schyler
    #   fonts:
    #     - asset: fonts/Schyler-Regular.ttf
    #     - asset: fonts/Schyler-Italic.ttf
    #       style: italic
    - family: InterstellarIcons
      fonts:
        - asset: assets/fonts/InterstellarIcons.ttf
